### ISSUE TITLE
Edit Component

### ISSUE THREAD

**Issue by AniAvazneli** [Girchi/elections-front#10]
Edit კომპონენტის გასაუმჯობესებლად გვჭირდება:

- [x] 1. პირადი ბალანსის თანხის ვიზუალის შესწორება რომ დიდ თანხაზე ჩანდეს სფეისები (10 000).
- [x] 2. ინფუთის დეფოლტ ისრების გაქრობა.
- [x] 3.  ინფუთში onChange-ზე თანხის ცვლილებისას პარალელურად იცვლება "გამოყოფილი საპარტიო თანხა" და ეგ რომ არ მოხდეს უნდა დავამატოთ ახალი useState და "გამოყოფილი საპარტიო თანხის" ცვლილება გავაკეთოთ მხოლოდ "დადასტურება ღილაკით onClick-ზე".
- [x] 4. ინფუთში ჩაწერილი თანხის ოდენობა შევზღუდოთ რომ არ იყოს არარეალურად დიდი ციფრი.

**Comment by dimachilaia** [comment]
done
