### ISSUE TITLE
კანდიდატის დამატება და მხარდაჭერის მინიჭება

### ISSUE THREAD

**Issue by AniAvazneli** [Girchi/elections-front#14]
- [x] 1. სელექთს შევუცვალოთ დეფოლტ სტილები : 
> > - [x] გამყოფი ხაზის გაქრობა.
> > - [x] კლიკზე ლურჯი ბორდერის მოშორება.
> > - [x] options- ჰოვერზე თითოეული პოლიტიკოსის სახელი უნდა გადადიოდეს სელექტიში(ზემოთ).
> > - [x] სელექთის სიგანის დაფიქსირება.
> > - [x] კანდიდატის ფოტო უნდა იყოს ცვალებადი თითოეულის პროფილის შესაბამისად.

**Comment by dimachilaia** [comment]
done
