### ISSUE TITLE
Rating List

### ISSUE THREAD

**Issue by AniAvazneli** [Girchi/elections-front#9]
- [x] Create RatingList folder in the components section.
- [x] Create Autorisation component.

- [x] Create PoliticalList component with 3 child components:

> 
> 1. [x] SearchPolitican - this part consists also headlines : გირჩის პარტიული სია && გირჩის პოტენციური პარტიული კანდიდატები და რეიტინგი.
> 2. [x] SortList - Add SortList component .
> 3. [x] SinglePolitican - Create SinglePolitican component with : 

> > 
>  > 1. [x] politican's image and full name.
>  > 2. [x] number of supporters and random 5 images of their.
>  > 3. [x] amount of GeD they are supporting a candidate.

- [x] Create PoliticansFullList component and put each SinglePolitican there.

**Comment by zanguraa** [comment]
only markup, without api has done.
